// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBczObmH2o4Tv0l3_eGpuGcBUwndBZ7xwI',
    appId: '1:198792802421:web:3da59001fceab9f5da883c',
    messagingSenderId: '198792802421',
    projectId: 'nightlife-platform-geek',
    authDomain: 'nightlife-platform-geek.firebaseapp.com',
    storageBucket: 'nightlife-platform-geek.firebasestorage.app',
    measurementId: 'G-BHY7CZRDNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAonRIyBO714EJCAaOxvAez7YAlre_kfW8',
    appId: '1:198792802421:android:208f8b5fd98f7cbeda883c',
    messagingSenderId: '198792802421',
    projectId: 'nightlife-platform-geek',
    storageBucket: 'nightlife-platform-geek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoNfEKZQPaRRD5kW9c0n2WC8omhF4jryU',
    appId: '1:198792802421:ios:d87f892e70fa2443da883c',
    messagingSenderId: '198792802421',
    projectId: 'nightlife-platform-geek',
    storageBucket: 'nightlife-platform-geek.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoNfEKZQPaRRD5kW9c0n2WC8omhF4jryU',
    appId: '1:198792802421:ios:d87f892e70fa2443da883c',
    messagingSenderId: '198792802421',
    projectId: 'nightlife-platform-geek',
    storageBucket: 'nightlife-platform-geek.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBczObmH2o4Tv0l3_eGpuGcBUwndBZ7xwI',
    appId: '1:198792802421:web:e71e4d1e63303372da883c',
    messagingSenderId: '198792802421',
    projectId: 'nightlife-platform-geek',
    authDomain: 'nightlife-platform-geek.firebaseapp.com',
    storageBucket: 'nightlife-platform-geek.firebasestorage.app',
    measurementId: 'G-ERHFVQZ0Z8',
  );
}
