// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdc6i_eRyu6AxWZ18L8H2xBtHndor8ZFU',
    appId: '1:338930228171:web:276218a4d4a2dd1b7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    authDomain: 'party-app-1774e.firebaseapp.com',
    storageBucket: 'party-app-1774e.firebasestorage.app',
    measurementId: 'G-EXYS4XL423',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2XS3CmknpO-Jgs0FdJ6ULSANofGMj8aE',
    appId: '1:338930228171:android:940bebef5070aedf7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    storageBucket: 'party-app-1774e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgv_iodE7dnjqs2oWYRq_PP5e40Wl13l0',
    appId: '1:338930228171:ios:b0cdf04b313b950a7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    storageBucket: 'party-app-1774e.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgv_iodE7dnjqs2oWYRq_PP5e40Wl13l0',
    appId: '1:338930228171:ios:b0cdf04b313b950a7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    storageBucket: 'party-app-1774e.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdc6i_eRyu6AxWZ18L8H2xBtHndor8ZFU',
    appId: '1:338930228171:web:7f0f2d3922ee8d8d7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    authDomain: 'party-app-1774e.firebaseapp.com',
    storageBucket: 'party-app-1774e.firebasestorage.app',
    measurementId: 'G-GM6R5VDMZG',
  );
}
