// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmEOkxjyqQ9B4ara8SZ_UL5cWMIzPbBQ',
    appId: '1:912634835284:web:d8a04f2a736c75dd2f18c1',
    messagingSenderId: '912634835284',
    projectId: 'party-app-4f142',
    authDomain: 'party-app-4f142.firebaseapp.com',
    storageBucket: 'party-app-4f142.firebasestorage.app',
    measurementId: 'G-3J37TRW1CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwrMRc0iOTGYexmCx8ljPHOAyvYvDigeY',
    appId: '1:912634835284:android:6fab9a4fef21773e2f18c1',
    messagingSenderId: '912634835284',
    projectId: 'party-app-4f142',
    storageBucket: 'party-app-4f142.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtdhajms0wCdKgHh7cliQZ4I7q-eNSsE',
    appId: '1:912634835284:ios:67f9253ace6313122f18c1',
    messagingSenderId: '912634835284',
    projectId: 'party-app-4f142',
    storageBucket: 'party-app-4f142.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtdhajms0wCdKgHh7cliQZ4I7q-eNSsE',
    appId: '1:912634835284:ios:67f9253ace6313122f18c1',
    messagingSenderId: '912634835284',
    projectId: 'party-app-4f142',
    storageBucket: 'party-app-4f142.firebasestorage.app',
    iosBundleId: 'com.example.nlFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQmEOkxjyqQ9B4ara8SZ_UL5cWMIzPbBQ',
    appId: '1:912634835284:web:c0d6fa0918df340e2f18c1',
    messagingSenderId: '912634835284',
    projectId: 'party-app-4f142',
    authDomain: 'party-app-4f142.firebaseapp.com',
    storageBucket: 'party-app-4f142.firebasestorage.app',
    measurementId: 'G-BLDL45T524',
  );
}
