// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'This admin app only supports web. '
      'Run it with `flutter run -d chrome`.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdc6i_eRyu6AxWZ18L8H2xBtHndor8ZFU',
    appId: '1:338930228171:web:276218a4d4a2dd1b7ff44e',
    messagingSenderId: '338930228171',
    projectId: 'party-app-1774e',
    authDomain: 'party-app-1774e.firebaseapp.com',
    storageBucket: 'party-app-1774e.firebasestorage.app',
    measurementId: 'G-EXYS4XL423',
  );
}
